config_particles:
  r_min: 4
  r_max: 20
  n_r: 128
  n_angles: 5
  n_split: 1

config_mad:
  # Links to be made for tools and scripts
  links:
    acc-models-lhc: /afs/cern.ch/eng/lhc/optics

  # Optics file
  optics_file: acc-models-lhc/runIII/RunIII_dev/ION_2024/opticsfile.21

  # Beam parameters
  beam_config:
    lhcb1:
      # Lead ions
      beam_energy_tot: 557600           # [GeV] corresponds to 6.8 Z TeV
      particle_mass: 193.6872729        # [GeV]
      particle_charge: 82
    lhcb2:
      # Lead ions
      beam_energy_tot: 557600           # [GeV] corresponds to 6.8 Z TeV
      particle_mass: 193.6872729        # [GeV]
      particle_charge: 82

  # Enable machine imperfections
  enable_imperfections: false

  # Enable knob synthesis (for coupling correction, if no imperfections)
  enable_knob_synthesis: true

  # Rename the coupling knobs to avoid conflict between b1 and b2
  # (for hllhc using old fortran code to generate the knobs)
  rename_coupling_knobs: true

  # Optics version, for choice of correction algorithms
  # (ver_lhc_run or ver_hllhc_optics)
  ver_hllhc_optics:
  ver_lhc_run: 3.0

  # Parameters for machine imperfections
  pars_for_imperfections:
    par_myseed: 1
    par_correct_for_D2: 0
    par_correct_for_MCBX: 0
    par_on_errors_LHC: 1
    par_off_errors_Q4_inIP15: 0
    par_off_errors_Q5_inIP15: 0
    par_on_errors_MBH: 1
    par_on_errors_Q4: 1
    par_on_errors_D2: 1
    par_on_errors_D1: 1
    par_on_errors_IT: 1
    par_on_errors_MCBRD: 0
    par_on_errors_MCBXF: 0
    par_on_errors_NLC: 0
    par_write_errortable: 1

# Context for the simulation
context: cpu   # 'cupy' # opencl

# Log
log_file: tree_maker.log

# To make some specifics checks
sanity_checks: true
